//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UserAccountActivities.Usermanagement {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserManagementSoap", Namespace="http://corridor.aero/cws/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CorridorStatusData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CorridorLoginData))]
    public partial class UserManagement : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeUserPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreatePermissionsProfileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserManagement() {
            this.Url = global::UserAccountActivities.Properties.Settings.Default.UserAccountActivities_vulcan_UserManagement;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddUserCompletedEventHandler AddUserCompleted;
        
        /// <remarks/>
        public event UpdateUserCompletedEventHandler UpdateUserCompleted;
        
        /// <remarks/>
        public event GetUserCompletedEventHandler GetUserCompleted;
        
        /// <remarks/>
        public event ChangeUserPasswordCompletedEventHandler ChangeUserPasswordCompleted;
        
        /// <remarks/>
        public event CreatePermissionsProfileCompletedEventHandler CreatePermissionsProfileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://corridor.aero/cws/AddUser", RequestNamespace="http://corridor.aero/cws/", ResponseNamespace="http://corridor.aero/cws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserManagementReferenceOutput AddUser(UserManagementData userData) {
            object[] results = this.Invoke("AddUser", new object[] {
                        userData});
            return ((UserManagementReferenceOutput)(results[0]));
        }
        
        /// <remarks/>
        public void AddUserAsync(UserManagementData userData) {
            this.AddUserAsync(userData, null);
        }
        
        /// <remarks/>
        public void AddUserAsync(UserManagementData userData, object userState) {
            if ((this.AddUserOperationCompleted == null)) {
                this.AddUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUserOperationCompleted);
            }
            this.InvokeAsync("AddUser", new object[] {
                        userData}, this.AddUserOperationCompleted, userState);
        }
        
        private void OnAddUserOperationCompleted(object arg) {
            if ((this.AddUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUserCompleted(this, new AddUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://corridor.aero/cws/UpdateUser", RequestNamespace="http://corridor.aero/cws/", ResponseNamespace="http://corridor.aero/cws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserManagementReferenceOutput UpdateUser(UserManagementUpdateData userData) {
            object[] results = this.Invoke("UpdateUser", new object[] {
                        userData});
            return ((UserManagementReferenceOutput)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserAsync(UserManagementUpdateData userData) {
            this.UpdateUserAsync(userData, null);
        }
        
        /// <remarks/>
        public void UpdateUserAsync(UserManagementUpdateData userData, object userState) {
            if ((this.UpdateUserOperationCompleted == null)) {
                this.UpdateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserOperationCompleted);
            }
            this.InvokeAsync("UpdateUser", new object[] {
                        userData}, this.UpdateUserOperationCompleted, userState);
        }
        
        private void OnUpdateUserOperationCompleted(object arg) {
            if ((this.UpdateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserCompleted(this, new UpdateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://corridor.aero/cws/GetUser", RequestNamespace="http://corridor.aero/cws/", ResponseNamespace="http://corridor.aero/cws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserManagementDataOutput GetUser(UserManagementReferenceInput userReference) {
            object[] results = this.Invoke("GetUser", new object[] {
                        userReference});
            return ((UserManagementDataOutput)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserAsync(UserManagementReferenceInput userReference) {
            this.GetUserAsync(userReference, null);
        }
        
        /// <remarks/>
        public void GetUserAsync(UserManagementReferenceInput userReference, object userState) {
            if ((this.GetUserOperationCompleted == null)) {
                this.GetUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserOperationCompleted);
            }
            this.InvokeAsync("GetUser", new object[] {
                        userReference}, this.GetUserOperationCompleted, userState);
        }
        
        private void OnGetUserOperationCompleted(object arg) {
            if ((this.GetUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserCompleted(this, new GetUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://corridor.aero/cws/ChangeUserPassword", RequestNamespace="http://corridor.aero/cws/", ResponseNamespace="http://corridor.aero/cws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserManagementReferenceOutput ChangeUserPassword(UserManagementChangePasswordInput userPasswdData) {
            object[] results = this.Invoke("ChangeUserPassword", new object[] {
                        userPasswdData});
            return ((UserManagementReferenceOutput)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeUserPasswordAsync(UserManagementChangePasswordInput userPasswdData) {
            this.ChangeUserPasswordAsync(userPasswdData, null);
        }
        
        /// <remarks/>
        public void ChangeUserPasswordAsync(UserManagementChangePasswordInput userPasswdData, object userState) {
            if ((this.ChangeUserPasswordOperationCompleted == null)) {
                this.ChangeUserPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeUserPasswordOperationCompleted);
            }
            this.InvokeAsync("ChangeUserPassword", new object[] {
                        userPasswdData}, this.ChangeUserPasswordOperationCompleted, userState);
        }
        
        private void OnChangeUserPasswordOperationCompleted(object arg) {
            if ((this.ChangeUserPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeUserPasswordCompleted(this, new ChangeUserPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://corridor.aero/cws/CreatePermissionsProfile", RequestNamespace="http://corridor.aero/cws/", ResponseNamespace="http://corridor.aero/cws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserManagementReferenceOutput CreatePermissionsProfile(UserManagementCreatePermissionsProfileInput userCreateProfileData) {
            object[] results = this.Invoke("CreatePermissionsProfile", new object[] {
                        userCreateProfileData});
            return ((UserManagementReferenceOutput)(results[0]));
        }
        
        /// <remarks/>
        public void CreatePermissionsProfileAsync(UserManagementCreatePermissionsProfileInput userCreateProfileData) {
            this.CreatePermissionsProfileAsync(userCreateProfileData, null);
        }
        
        /// <remarks/>
        public void CreatePermissionsProfileAsync(UserManagementCreatePermissionsProfileInput userCreateProfileData, object userState) {
            if ((this.CreatePermissionsProfileOperationCompleted == null)) {
                this.CreatePermissionsProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePermissionsProfileOperationCompleted);
            }
            this.InvokeAsync("CreatePermissionsProfile", new object[] {
                        userCreateProfileData}, this.CreatePermissionsProfileOperationCompleted, userState);
        }
        
        private void OnCreatePermissionsProfileOperationCompleted(object arg) {
            if ((this.CreatePermissionsProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreatePermissionsProfileCompleted(this, new CreatePermissionsProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementUpdateData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserManagementData : CorridorLoginData {
        
        private string usernameField;
        
        private string fullnameField;
        
        private string descriptionField;
        
        private string departmentField;
        
        private string userBadgeIDField;
        
        private string passwordField;
        
        private string accessCodeField;
        
        private string activeDirectoryNameField;
        
        private string userPermissionsProfileField;
        
        private UserDefinedField[] userDefinedFieldsField;
        
        private string defaultScreenField;
        
        private double purchaseLimitField;
        
        private double laborCostField;
        
        private double regularCostField;
        
        private double overtimeCostField;
        
        private double doubleTimeCostField;
        
        private double regularBurdenCostField;
        
        private double overtimeBurdenCostField;
        
        private double doubleTimeBurdenCostField;
        
        private string regularLaborAccountNumberField;
        
        private string overtimeLaborAccountNumberField;
        
        private string doubleTimeLaborAccountNumberField;
        
        private string laborBurdenAccountNumberField;
        
        private bool mustChangePasswordField;
        
        private bool mustChangeAccessCodeField;
        
        private bool cannotChangePasswordField;
        
        private bool accountDisabledField;
        
        private bool locatorField;
        
        private bool suspendLocatorField;
        
        private bool canSelectLocatorField;
        
        private bool canSelectToVendorLotField;
        
        private bool receivingInspectorField;
        
        private bool tipOfDayField;
        
        private bool largeButtonsField;
        
        private bool disablePersistenceField;
        
        private bool defaultIncludeFuelActivityField;
        
        private bool onlyIncludeFuelActivityField;
        
        private bool defaultIncludeServiceActivityField;
        
        private bool onlyIncludeServiceActivityField;
        
        private bool defaultIncludePartSaleActivityField;
        
        private bool onlyIncludePartSaleActivityField;
        
        private bool defaultIncludeCateringActivityField;
        
        private bool onlyIncludeCateringActivityField;
        
        private bool defaultIncludeHotelActivityField;
        
        private bool onlyIncludeHotelActivityField;
        
        private bool defaultIncludeTransportationActivityField;
        
        private bool onlyIncludeTransportationActivityField;
        
        private bool launchLogbookResearchField;
        
        private bool canEnterComplianceField;
        
        private bool includeAllDefaultLogbookSearchCriteriaField;
        
        private bool onlyDisplayAssignedInWOQMgmtField;
        
        public UserManagementData() {
            this.purchaseLimitField = -99999.99999D;
            this.laborCostField = -99999.99999D;
            this.regularCostField = -99999.99999D;
            this.overtimeCostField = -99999.99999D;
            this.doubleTimeCostField = -99999.99999D;
            this.regularBurdenCostField = -99999.99999D;
            this.overtimeBurdenCostField = -99999.99999D;
            this.doubleTimeBurdenCostField = -99999.99999D;
            this.mustChangePasswordField = false;
            this.mustChangeAccessCodeField = false;
            this.cannotChangePasswordField = false;
            this.accountDisabledField = false;
            this.locatorField = false;
            this.suspendLocatorField = false;
            this.canSelectLocatorField = false;
            this.canSelectToVendorLotField = false;
            this.receivingInspectorField = false;
            this.tipOfDayField = false;
            this.largeButtonsField = false;
            this.disablePersistenceField = false;
            this.defaultIncludeFuelActivityField = false;
            this.onlyIncludeFuelActivityField = false;
            this.defaultIncludeServiceActivityField = false;
            this.onlyIncludeServiceActivityField = false;
            this.defaultIncludePartSaleActivityField = false;
            this.onlyIncludePartSaleActivityField = false;
            this.defaultIncludeCateringActivityField = false;
            this.onlyIncludeCateringActivityField = false;
            this.defaultIncludeHotelActivityField = false;
            this.onlyIncludeHotelActivityField = false;
            this.defaultIncludeTransportationActivityField = false;
            this.onlyIncludeTransportationActivityField = false;
            this.launchLogbookResearchField = false;
            this.canEnterComplianceField = false;
            this.includeAllDefaultLogbookSearchCriteriaField = false;
            this.onlyDisplayAssignedInWOQMgmtField = false;
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string UserBadgeID {
            get {
                return this.userBadgeIDField;
            }
            set {
                this.userBadgeIDField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string AccessCode {
            get {
                return this.accessCodeField;
            }
            set {
                this.accessCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ActiveDirectoryName {
            get {
                return this.activeDirectoryNameField;
            }
            set {
                this.activeDirectoryNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserPermissionsProfile {
            get {
                return this.userPermissionsProfileField;
            }
            set {
                this.userPermissionsProfileField = value;
            }
        }
        
        /// <remarks/>
        public UserDefinedField[] UserDefinedFields {
            get {
                return this.userDefinedFieldsField;
            }
            set {
                this.userDefinedFieldsField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultScreen {
            get {
                return this.defaultScreenField;
            }
            set {
                this.defaultScreenField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-99999.99999D)]
        public double PurchaseLimit {
            get {
                return this.purchaseLimitField;
            }
            set {
                this.purchaseLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-99999.99999D)]
        public double LaborCost {
            get {
                return this.laborCostField;
            }
            set {
                this.laborCostField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-99999.99999D)]
        public double RegularCost {
            get {
                return this.regularCostField;
            }
            set {
                this.regularCostField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-99999.99999D)]
        public double OvertimeCost {
            get {
                return this.overtimeCostField;
            }
            set {
                this.overtimeCostField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-99999.99999D)]
        public double DoubleTimeCost {
            get {
                return this.doubleTimeCostField;
            }
            set {
                this.doubleTimeCostField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-99999.99999D)]
        public double RegularBurdenCost {
            get {
                return this.regularBurdenCostField;
            }
            set {
                this.regularBurdenCostField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-99999.99999D)]
        public double OvertimeBurdenCost {
            get {
                return this.overtimeBurdenCostField;
            }
            set {
                this.overtimeBurdenCostField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(-99999.99999D)]
        public double DoubleTimeBurdenCost {
            get {
                return this.doubleTimeBurdenCostField;
            }
            set {
                this.doubleTimeBurdenCostField = value;
            }
        }
        
        /// <remarks/>
        public string RegularLaborAccountNumber {
            get {
                return this.regularLaborAccountNumberField;
            }
            set {
                this.regularLaborAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string OvertimeLaborAccountNumber {
            get {
                return this.overtimeLaborAccountNumberField;
            }
            set {
                this.overtimeLaborAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DoubleTimeLaborAccountNumber {
            get {
                return this.doubleTimeLaborAccountNumberField;
            }
            set {
                this.doubleTimeLaborAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LaborBurdenAccountNumber {
            get {
                return this.laborBurdenAccountNumberField;
            }
            set {
                this.laborBurdenAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool MustChangePassword {
            get {
                return this.mustChangePasswordField;
            }
            set {
                this.mustChangePasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool MustChangeAccessCode {
            get {
                return this.mustChangeAccessCodeField;
            }
            set {
                this.mustChangeAccessCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CannotChangePassword {
            get {
                return this.cannotChangePasswordField;
            }
            set {
                this.cannotChangePasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool AccountDisabled {
            get {
                return this.accountDisabledField;
            }
            set {
                this.accountDisabledField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Locator {
            get {
                return this.locatorField;
            }
            set {
                this.locatorField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SuspendLocator {
            get {
                return this.suspendLocatorField;
            }
            set {
                this.suspendLocatorField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CanSelectLocator {
            get {
                return this.canSelectLocatorField;
            }
            set {
                this.canSelectLocatorField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CanSelectToVendorLot {
            get {
                return this.canSelectToVendorLotField;
            }
            set {
                this.canSelectToVendorLotField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReceivingInspector {
            get {
                return this.receivingInspectorField;
            }
            set {
                this.receivingInspectorField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool TipOfDay {
            get {
                return this.tipOfDayField;
            }
            set {
                this.tipOfDayField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool LargeButtons {
            get {
                return this.largeButtonsField;
            }
            set {
                this.largeButtonsField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DisablePersistence {
            get {
                return this.disablePersistenceField;
            }
            set {
                this.disablePersistenceField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DefaultIncludeFuelActivity {
            get {
                return this.defaultIncludeFuelActivityField;
            }
            set {
                this.defaultIncludeFuelActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OnlyIncludeFuelActivity {
            get {
                return this.onlyIncludeFuelActivityField;
            }
            set {
                this.onlyIncludeFuelActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DefaultIncludeServiceActivity {
            get {
                return this.defaultIncludeServiceActivityField;
            }
            set {
                this.defaultIncludeServiceActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OnlyIncludeServiceActivity {
            get {
                return this.onlyIncludeServiceActivityField;
            }
            set {
                this.onlyIncludeServiceActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DefaultIncludePartSaleActivity {
            get {
                return this.defaultIncludePartSaleActivityField;
            }
            set {
                this.defaultIncludePartSaleActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OnlyIncludePartSaleActivity {
            get {
                return this.onlyIncludePartSaleActivityField;
            }
            set {
                this.onlyIncludePartSaleActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DefaultIncludeCateringActivity {
            get {
                return this.defaultIncludeCateringActivityField;
            }
            set {
                this.defaultIncludeCateringActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OnlyIncludeCateringActivity {
            get {
                return this.onlyIncludeCateringActivityField;
            }
            set {
                this.onlyIncludeCateringActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DefaultIncludeHotelActivity {
            get {
                return this.defaultIncludeHotelActivityField;
            }
            set {
                this.defaultIncludeHotelActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OnlyIncludeHotelActivity {
            get {
                return this.onlyIncludeHotelActivityField;
            }
            set {
                this.onlyIncludeHotelActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool DefaultIncludeTransportationActivity {
            get {
                return this.defaultIncludeTransportationActivityField;
            }
            set {
                this.defaultIncludeTransportationActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OnlyIncludeTransportationActivity {
            get {
                return this.onlyIncludeTransportationActivityField;
            }
            set {
                this.onlyIncludeTransportationActivityField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool LaunchLogbookResearch {
            get {
                return this.launchLogbookResearchField;
            }
            set {
                this.launchLogbookResearchField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool CanEnterCompliance {
            get {
                return this.canEnterComplianceField;
            }
            set {
                this.canEnterComplianceField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool IncludeAllDefaultLogbookSearchCriteria {
            get {
                return this.includeAllDefaultLogbookSearchCriteriaField;
            }
            set {
                this.includeAllDefaultLogbookSearchCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool OnlyDisplayAssignedInWOQMgmt {
            get {
                return this.onlyDisplayAssignedInWOQMgmtField;
            }
            set {
                this.onlyDisplayAssignedInWOQMgmtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserDefinedField {
        
        private string labelField;
        
        private string dataField;
        
        /// <remarks/>
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class ErrorMessage {
        
        private string errorTextField;
        
        private int errorCodeField;
        
        /// <remarks/>
        public string ErrorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementDataOutput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementReferenceOutput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class CorridorStatusData {
        
        private string statusMessageField;
        
        private ErrorMessage[] errorMessagesField;
        
        /// <remarks/>
        public string StatusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
            }
        }
        
        /// <remarks/>
        public ErrorMessage[] ErrorMessages {
            get {
                return this.errorMessagesField;
            }
            set {
                this.errorMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserManagementDataOutput : CorridorStatusData {
        
        private string usernameField;
        
        private long userKeyField;
        
        private string purchaseLimitField;
        
        private string regularCostField;
        
        private string overtimeCostField;
        
        private string doubleTimeCostField;
        
        private string regularBurdenCostField;
        
        private string overtimeBurdenCostField;
        
        private string doubleTimeBurdenCostField;
        
        private string fullnameField;
        
        private string descriptionField;
        
        private string departmentField;
        
        private string userBadgeIDField;
        
        private string activeDirectoryNameField;
        
        private string userPermissionsProfileField;
        
        private UserDefinedField[] userDefinedFieldsField;
        
        private string regularLaborAccountNumberField;
        
        private string overtimeLaborAccountNumberField;
        
        private string doubleTimeLaborAccountNumberField;
        
        private string laborBurdenAccountNumberField;
        
        private string defaultScreenField;
        
        private bool mustChangePasswordField;
        
        private bool cannotChangePasswordField;
        
        private bool accountDisabledField;
        
        private bool locatorField;
        
        private bool suspendLocatorField;
        
        private bool canSelectLocatorField;
        
        private bool canSelectToVendorLotField;
        
        private bool receivingInspectorField;
        
        private bool tipOfDayField;
        
        private bool largeButtonsField;
        
        private bool disablePersistenceField;
        
        private bool defaultIncludeFuelActivityField;
        
        private bool onlyIncludeFuelActivityField;
        
        private bool defaultIncludeServiceActivityField;
        
        private bool onlyIncludeServiceActivityField;
        
        private bool defaultIncludePartSaleActivityField;
        
        private bool onlyIncludePartSaleActivityField;
        
        private bool defaultIncludeCateringActivityField;
        
        private bool onlyIncludeCateringActivityField;
        
        private bool defaultIncludeHotelActivityField;
        
        private bool onlyIncludeHotelActivityField;
        
        private bool defaultIncludeTransportationActivityField;
        
        private bool onlyIncludeTransportationActivityField;
        
        private bool launchLogbookResearchField;
        
        private bool canEnterComplianceField;
        
        private bool includeAllDefaultLogbookSearchCriteriaField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public long UserKey {
            get {
                return this.userKeyField;
            }
            set {
                this.userKeyField = value;
            }
        }
        
        /// <remarks/>
        public string PurchaseLimit {
            get {
                return this.purchaseLimitField;
            }
            set {
                this.purchaseLimitField = value;
            }
        }
        
        /// <remarks/>
        public string RegularCost {
            get {
                return this.regularCostField;
            }
            set {
                this.regularCostField = value;
            }
        }
        
        /// <remarks/>
        public string OvertimeCost {
            get {
                return this.overtimeCostField;
            }
            set {
                this.overtimeCostField = value;
            }
        }
        
        /// <remarks/>
        public string DoubleTimeCost {
            get {
                return this.doubleTimeCostField;
            }
            set {
                this.doubleTimeCostField = value;
            }
        }
        
        /// <remarks/>
        public string RegularBurdenCost {
            get {
                return this.regularBurdenCostField;
            }
            set {
                this.regularBurdenCostField = value;
            }
        }
        
        /// <remarks/>
        public string OvertimeBurdenCost {
            get {
                return this.overtimeBurdenCostField;
            }
            set {
                this.overtimeBurdenCostField = value;
            }
        }
        
        /// <remarks/>
        public string DoubleTimeBurdenCost {
            get {
                return this.doubleTimeBurdenCostField;
            }
            set {
                this.doubleTimeBurdenCostField = value;
            }
        }
        
        /// <remarks/>
        public string Fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string UserBadgeID {
            get {
                return this.userBadgeIDField;
            }
            set {
                this.userBadgeIDField = value;
            }
        }
        
        /// <remarks/>
        public string ActiveDirectoryName {
            get {
                return this.activeDirectoryNameField;
            }
            set {
                this.activeDirectoryNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserPermissionsProfile {
            get {
                return this.userPermissionsProfileField;
            }
            set {
                this.userPermissionsProfileField = value;
            }
        }
        
        /// <remarks/>
        public UserDefinedField[] UserDefinedFields {
            get {
                return this.userDefinedFieldsField;
            }
            set {
                this.userDefinedFieldsField = value;
            }
        }
        
        /// <remarks/>
        public string RegularLaborAccountNumber {
            get {
                return this.regularLaborAccountNumberField;
            }
            set {
                this.regularLaborAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string OvertimeLaborAccountNumber {
            get {
                return this.overtimeLaborAccountNumberField;
            }
            set {
                this.overtimeLaborAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DoubleTimeLaborAccountNumber {
            get {
                return this.doubleTimeLaborAccountNumberField;
            }
            set {
                this.doubleTimeLaborAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LaborBurdenAccountNumber {
            get {
                return this.laborBurdenAccountNumberField;
            }
            set {
                this.laborBurdenAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultScreen {
            get {
                return this.defaultScreenField;
            }
            set {
                this.defaultScreenField = value;
            }
        }
        
        /// <remarks/>
        public bool MustChangePassword {
            get {
                return this.mustChangePasswordField;
            }
            set {
                this.mustChangePasswordField = value;
            }
        }
        
        /// <remarks/>
        public bool CannotChangePassword {
            get {
                return this.cannotChangePasswordField;
            }
            set {
                this.cannotChangePasswordField = value;
            }
        }
        
        /// <remarks/>
        public bool AccountDisabled {
            get {
                return this.accountDisabledField;
            }
            set {
                this.accountDisabledField = value;
            }
        }
        
        /// <remarks/>
        public bool Locator {
            get {
                return this.locatorField;
            }
            set {
                this.locatorField = value;
            }
        }
        
        /// <remarks/>
        public bool SuspendLocator {
            get {
                return this.suspendLocatorField;
            }
            set {
                this.suspendLocatorField = value;
            }
        }
        
        /// <remarks/>
        public bool CanSelectLocator {
            get {
                return this.canSelectLocatorField;
            }
            set {
                this.canSelectLocatorField = value;
            }
        }
        
        /// <remarks/>
        public bool CanSelectToVendorLot {
            get {
                return this.canSelectToVendorLotField;
            }
            set {
                this.canSelectToVendorLotField = value;
            }
        }
        
        /// <remarks/>
        public bool ReceivingInspector {
            get {
                return this.receivingInspectorField;
            }
            set {
                this.receivingInspectorField = value;
            }
        }
        
        /// <remarks/>
        public bool TipOfDay {
            get {
                return this.tipOfDayField;
            }
            set {
                this.tipOfDayField = value;
            }
        }
        
        /// <remarks/>
        public bool LargeButtons {
            get {
                return this.largeButtonsField;
            }
            set {
                this.largeButtonsField = value;
            }
        }
        
        /// <remarks/>
        public bool DisablePersistence {
            get {
                return this.disablePersistenceField;
            }
            set {
                this.disablePersistenceField = value;
            }
        }
        
        /// <remarks/>
        public bool DefaultIncludeFuelActivity {
            get {
                return this.defaultIncludeFuelActivityField;
            }
            set {
                this.defaultIncludeFuelActivityField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlyIncludeFuelActivity {
            get {
                return this.onlyIncludeFuelActivityField;
            }
            set {
                this.onlyIncludeFuelActivityField = value;
            }
        }
        
        /// <remarks/>
        public bool DefaultIncludeServiceActivity {
            get {
                return this.defaultIncludeServiceActivityField;
            }
            set {
                this.defaultIncludeServiceActivityField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlyIncludeServiceActivity {
            get {
                return this.onlyIncludeServiceActivityField;
            }
            set {
                this.onlyIncludeServiceActivityField = value;
            }
        }
        
        /// <remarks/>
        public bool DefaultIncludePartSaleActivity {
            get {
                return this.defaultIncludePartSaleActivityField;
            }
            set {
                this.defaultIncludePartSaleActivityField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlyIncludePartSaleActivity {
            get {
                return this.onlyIncludePartSaleActivityField;
            }
            set {
                this.onlyIncludePartSaleActivityField = value;
            }
        }
        
        /// <remarks/>
        public bool DefaultIncludeCateringActivity {
            get {
                return this.defaultIncludeCateringActivityField;
            }
            set {
                this.defaultIncludeCateringActivityField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlyIncludeCateringActivity {
            get {
                return this.onlyIncludeCateringActivityField;
            }
            set {
                this.onlyIncludeCateringActivityField = value;
            }
        }
        
        /// <remarks/>
        public bool DefaultIncludeHotelActivity {
            get {
                return this.defaultIncludeHotelActivityField;
            }
            set {
                this.defaultIncludeHotelActivityField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlyIncludeHotelActivity {
            get {
                return this.onlyIncludeHotelActivityField;
            }
            set {
                this.onlyIncludeHotelActivityField = value;
            }
        }
        
        /// <remarks/>
        public bool DefaultIncludeTransportationActivity {
            get {
                return this.defaultIncludeTransportationActivityField;
            }
            set {
                this.defaultIncludeTransportationActivityField = value;
            }
        }
        
        /// <remarks/>
        public bool OnlyIncludeTransportationActivity {
            get {
                return this.onlyIncludeTransportationActivityField;
            }
            set {
                this.onlyIncludeTransportationActivityField = value;
            }
        }
        
        /// <remarks/>
        public bool LaunchLogbookResearch {
            get {
                return this.launchLogbookResearchField;
            }
            set {
                this.launchLogbookResearchField = value;
            }
        }
        
        /// <remarks/>
        public bool CanEnterCompliance {
            get {
                return this.canEnterComplianceField;
            }
            set {
                this.canEnterComplianceField = value;
            }
        }
        
        /// <remarks/>
        public bool IncludeAllDefaultLogbookSearchCriteria {
            get {
                return this.includeAllDefaultLogbookSearchCriteriaField;
            }
            set {
                this.includeAllDefaultLogbookSearchCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserManagementReferenceOutput : CorridorStatusData {
        
        private string usernameField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementChangePasswordInput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementReferenceInput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementCreatePermissionsProfileInput))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementUpdateData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class CorridorLoginData {
        
        private string aliasNameField;
        
        private string loginIDField;
        
        private string loginPasswordField;
        
        private string sessionTokenField;
        
        /// <remarks/>
        public string AliasName {
            get {
                return this.aliasNameField;
            }
            set {
                this.aliasNameField = value;
            }
        }
        
        /// <remarks/>
        public string LoginID {
            get {
                return this.loginIDField;
            }
            set {
                this.loginIDField = value;
            }
        }
        
        /// <remarks/>
        public string LoginPassword {
            get {
                return this.loginPasswordField;
            }
            set {
                this.loginPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string SessionToken {
            get {
                return this.sessionTokenField;
            }
            set {
                this.sessionTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserManagementChangePasswordInput : CorridorLoginData {
        
        private string usernameField;
        
        private string passwordField;
        
        private string newPasswordField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string NewPassword {
            get {
                return this.newPasswordField;
            }
            set {
                this.newPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserManagementCreatePermissionsProfileInput))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserManagementReferenceInput : CorridorLoginData {
        
        private string usernameField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserManagementCreatePermissionsProfileInput : UserManagementReferenceInput {
        
        private string createPermissionsProfileNameField;
        
        private bool setUserPermissionsProfileToNewField;
        
        public UserManagementCreatePermissionsProfileInput() {
            this.setUserPermissionsProfileToNewField = false;
        }
        
        /// <remarks/>
        public string CreatePermissionsProfileName {
            get {
                return this.createPermissionsProfileNameField;
            }
            set {
                this.createPermissionsProfileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SetUserPermissionsProfileToNew {
            get {
                return this.setUserPermissionsProfileToNewField;
            }
            set {
                this.setUserPermissionsProfileToNewField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://corridor.aero/cws/")]
    public partial class UserManagementUpdateData : UserManagementData {
        
        private string newUsernameField;
        
        /// <remarks/>
        public string NewUsername {
            get {
                return this.newUsernameField;
            }
            set {
                this.newUsernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AddUserCompletedEventHandler(object sender, AddUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserManagementReferenceOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserManagementReferenceOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UpdateUserCompletedEventHandler(object sender, UpdateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserManagementReferenceOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserManagementReferenceOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetUserCompletedEventHandler(object sender, GetUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserManagementDataOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserManagementDataOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ChangeUserPasswordCompletedEventHandler(object sender, ChangeUserPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeUserPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeUserPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserManagementReferenceOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserManagementReferenceOutput)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CreatePermissionsProfileCompletedEventHandler(object sender, CreatePermissionsProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreatePermissionsProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreatePermissionsProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserManagementReferenceOutput Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserManagementReferenceOutput)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591